/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IERC20Bytes32 } from "./IERC20Bytes32";

export class IERC20Bytes32Factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC20Bytes32 {
    return new Contract(address, _abi, signerOrProvider) as IERC20Bytes32;
  }
}

const _abi = [
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
