/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface OracleRouterInterface extends ethers.utils.Interface {
  functions: {
    "collateral()": FunctionFragment;
    "dumpPath()": FunctionFragment;
    "getPath()": FunctionFragment;
    "isMarketClosed()": FunctionFragment;
    "isTerminated()": FunctionFragment;
    "priceTWAPLong()": FunctionFragment;
    "priceTWAPShort()": FunctionFragment;
    "source()": FunctionFragment;
    "underlyingAsset()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "collateral",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dumpPath", values?: undefined): string;
  encodeFunctionData(functionFragment: "getPath", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isMarketClosed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTerminated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceTWAPLong",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceTWAPShort",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "source", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "underlyingAsset",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "collateral", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dumpPath", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPath", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isMarketClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTerminated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceTWAPLong",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceTWAPShort",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "source", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "underlyingAsset",
    data: BytesLike
  ): Result;

  events: {};
}

export class OracleRouter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: OracleRouterInterface;

  functions: {
    collateral(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "collateral()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    dumpPath(overrides?: CallOverrides): Promise<{
      0: {
        oracle: string;
        isInverse: boolean;
        underlyingAsset: string;
        collateral: string;
        0: string;
        1: boolean;
        2: string;
        3: string;
      }[];
    }>;

    "dumpPath()"(overrides?: CallOverrides): Promise<{
      0: {
        oracle: string;
        isInverse: boolean;
        underlyingAsset: string;
        collateral: string;
        0: string;
        1: boolean;
        2: string;
        3: string;
      }[];
    }>;

    getPath(overrides?: CallOverrides): Promise<{
      0: { oracle: string; isInverse: boolean; 0: string; 1: boolean }[];
    }>;

    "getPath()"(overrides?: CallOverrides): Promise<{
      0: { oracle: string; isInverse: boolean; 0: string; 1: boolean }[];
    }>;

    isMarketClosed(overrides?: Overrides): Promise<ContractTransaction>;

    "isMarketClosed()"(overrides?: Overrides): Promise<ContractTransaction>;

    isTerminated(overrides?: Overrides): Promise<ContractTransaction>;

    "isTerminated()"(overrides?: Overrides): Promise<ContractTransaction>;

    priceTWAPLong(overrides?: Overrides): Promise<ContractTransaction>;

    "priceTWAPLong()"(overrides?: Overrides): Promise<ContractTransaction>;

    priceTWAPShort(overrides?: Overrides): Promise<ContractTransaction>;

    "priceTWAPShort()"(overrides?: Overrides): Promise<ContractTransaction>;

    source(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "source()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    underlyingAsset(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "underlyingAsset()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;
  };

  collateral(overrides?: CallOverrides): Promise<string>;

  "collateral()"(overrides?: CallOverrides): Promise<string>;

  dumpPath(
    overrides?: CallOverrides
  ): Promise<
    {
      oracle: string;
      isInverse: boolean;
      underlyingAsset: string;
      collateral: string;
      0: string;
      1: boolean;
      2: string;
      3: string;
    }[]
  >;

  "dumpPath()"(
    overrides?: CallOverrides
  ): Promise<
    {
      oracle: string;
      isInverse: boolean;
      underlyingAsset: string;
      collateral: string;
      0: string;
      1: boolean;
      2: string;
      3: string;
    }[]
  >;

  getPath(
    overrides?: CallOverrides
  ): Promise<{ oracle: string; isInverse: boolean; 0: string; 1: boolean }[]>;

  "getPath()"(
    overrides?: CallOverrides
  ): Promise<{ oracle: string; isInverse: boolean; 0: string; 1: boolean }[]>;

  isMarketClosed(overrides?: Overrides): Promise<ContractTransaction>;

  "isMarketClosed()"(overrides?: Overrides): Promise<ContractTransaction>;

  isTerminated(overrides?: Overrides): Promise<ContractTransaction>;

  "isTerminated()"(overrides?: Overrides): Promise<ContractTransaction>;

  priceTWAPLong(overrides?: Overrides): Promise<ContractTransaction>;

  "priceTWAPLong()"(overrides?: Overrides): Promise<ContractTransaction>;

  priceTWAPShort(overrides?: Overrides): Promise<ContractTransaction>;

  "priceTWAPShort()"(overrides?: Overrides): Promise<ContractTransaction>;

  source(overrides?: CallOverrides): Promise<string>;

  "source()"(overrides?: CallOverrides): Promise<string>;

  underlyingAsset(overrides?: CallOverrides): Promise<string>;

  "underlyingAsset()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    collateral(overrides?: CallOverrides): Promise<string>;

    "collateral()"(overrides?: CallOverrides): Promise<string>;

    dumpPath(
      overrides?: CallOverrides
    ): Promise<
      {
        oracle: string;
        isInverse: boolean;
        underlyingAsset: string;
        collateral: string;
        0: string;
        1: boolean;
        2: string;
        3: string;
      }[]
    >;

    "dumpPath()"(
      overrides?: CallOverrides
    ): Promise<
      {
        oracle: string;
        isInverse: boolean;
        underlyingAsset: string;
        collateral: string;
        0: string;
        1: boolean;
        2: string;
        3: string;
      }[]
    >;

    getPath(
      overrides?: CallOverrides
    ): Promise<{ oracle: string; isInverse: boolean; 0: string; 1: boolean }[]>;

    "getPath()"(
      overrides?: CallOverrides
    ): Promise<{ oracle: string; isInverse: boolean; 0: string; 1: boolean }[]>;

    isMarketClosed(overrides?: CallOverrides): Promise<boolean>;

    "isMarketClosed()"(overrides?: CallOverrides): Promise<boolean>;

    isTerminated(overrides?: CallOverrides): Promise<boolean>;

    "isTerminated()"(overrides?: CallOverrides): Promise<boolean>;

    priceTWAPLong(overrides?: CallOverrides): Promise<{
      newPrice: BigNumber;
      newTimestamp: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "priceTWAPLong()"(overrides?: CallOverrides): Promise<{
      newPrice: BigNumber;
      newTimestamp: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    priceTWAPShort(overrides?: CallOverrides): Promise<{
      newPrice: BigNumber;
      newTimestamp: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    "priceTWAPShort()"(overrides?: CallOverrides): Promise<{
      newPrice: BigNumber;
      newTimestamp: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    source(overrides?: CallOverrides): Promise<string>;

    "source()"(overrides?: CallOverrides): Promise<string>;

    underlyingAsset(overrides?: CallOverrides): Promise<string>;

    "underlyingAsset()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    collateral(overrides?: CallOverrides): Promise<BigNumber>;

    "collateral()"(overrides?: CallOverrides): Promise<BigNumber>;

    dumpPath(overrides?: CallOverrides): Promise<BigNumber>;

    "dumpPath()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPath(overrides?: CallOverrides): Promise<BigNumber>;

    "getPath()"(overrides?: CallOverrides): Promise<BigNumber>;

    isMarketClosed(overrides?: Overrides): Promise<BigNumber>;

    "isMarketClosed()"(overrides?: Overrides): Promise<BigNumber>;

    isTerminated(overrides?: Overrides): Promise<BigNumber>;

    "isTerminated()"(overrides?: Overrides): Promise<BigNumber>;

    priceTWAPLong(overrides?: Overrides): Promise<BigNumber>;

    "priceTWAPLong()"(overrides?: Overrides): Promise<BigNumber>;

    priceTWAPShort(overrides?: Overrides): Promise<BigNumber>;

    "priceTWAPShort()"(overrides?: Overrides): Promise<BigNumber>;

    source(overrides?: CallOverrides): Promise<BigNumber>;

    "source()"(overrides?: CallOverrides): Promise<BigNumber>;

    underlyingAsset(overrides?: CallOverrides): Promise<BigNumber>;

    "underlyingAsset()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    collateral(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "collateral()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dumpPath(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "dumpPath()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPath(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getPath()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isMarketClosed(overrides?: Overrides): Promise<PopulatedTransaction>;

    "isMarketClosed()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    isTerminated(overrides?: Overrides): Promise<PopulatedTransaction>;

    "isTerminated()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    priceTWAPLong(overrides?: Overrides): Promise<PopulatedTransaction>;

    "priceTWAPLong()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    priceTWAPShort(overrides?: Overrides): Promise<PopulatedTransaction>;

    "priceTWAPShort()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    source(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "source()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    underlyingAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "underlyingAsset()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
