/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { OracleRouterCreator } from "./OracleRouterCreator";

export class OracleRouterCreatorFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OracleRouterCreator {
    return new Contract(address, _abi, signerOrProvider) as OracleRouterCreator;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "router",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "collateral",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "underlyingAsset",
        type: "string",
      },
      {
        components: [
          {
            internalType: "address",
            name: "oracle",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isInverse",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct OracleRouter.Route[]",
        name: "path",
        type: "tuple[]",
      },
    ],
    name: "NewOracleRouter",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "oracle",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isInverse",
            type: "bool",
          },
        ],
        internalType: "struct OracleRouter.Route[]",
        name: "path",
        type: "tuple[]",
      },
    ],
    name: "createOracleRouter",
    outputs: [
      {
        internalType: "address",
        name: "instance",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "oracle",
            type: "address",
          },
          {
            internalType: "bool",
            name: "isInverse",
            type: "bool",
          },
        ],
        internalType: "struct OracleRouter.Route[]",
        name: "path",
        type: "tuple[]",
      },
    ],
    name: "getPathHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "routers",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
