/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { UniswapV3Tool } from "./UniswapV3Tool";

export class UniswapV3ToolFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniswapV3Tool {
    return new Contract(address, _abi, signerOrProvider) as UniswapV3Tool;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "path",
        type: "address[]",
      },
      {
        internalType: "uint24[]",
        name: "fees",
        type: "uint24[]",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "path",
        type: "address[]",
      },
      {
        internalType: "uint24[]",
        name: "fees",
        type: "uint24[]",
      },
      {
        internalType: "uint16",
        name: "observationCardinalityNext",
        type: "uint16",
      },
    ],
    name: "increaseObservationCardinalityNext",
    outputs: [
      {
        internalType: "uint256",
        name: "totalIncreasedObservationCardinalityNext",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
