/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface UniswapV3ToolInterface extends ethers.utils.Interface {
  functions: {
    "getPrice(address,address[],uint24[])": FunctionFragment;
    "increaseObservationCardinalityNext(address,address[],uint24[],uint16)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getPrice",
    values: [string, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseObservationCardinalityNext",
    values: [string, string[], BigNumberish[], BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseObservationCardinalityNext",
    data: BytesLike
  ): Result;

  events: {};
}

export class UniswapV3Tool extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: UniswapV3ToolInterface;

  functions: {
    getPrice(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getPrice(address,address[],uint24[])"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    increaseObservationCardinalityNext(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "increaseObservationCardinalityNext(address,address[],uint24[],uint16)"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getPrice(
    factory: string,
    path: string[],
    fees: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getPrice(address,address[],uint24[])"(
    factory: string,
    path: string[],
    fees: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  increaseObservationCardinalityNext(
    factory: string,
    path: string[],
    fees: BigNumberish[],
    observationCardinalityNext: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "increaseObservationCardinalityNext(address,address[],uint24[],uint16)"(
    factory: string,
    path: string[],
    fees: BigNumberish[],
    observationCardinalityNext: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getPrice(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrice(address,address[],uint24[])"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseObservationCardinalityNext(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "increaseObservationCardinalityNext(address,address[],uint24[],uint16)"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getPrice(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrice(address,address[],uint24[])"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseObservationCardinalityNext(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "increaseObservationCardinalityNext(address,address[],uint24[],uint16)"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPrice(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPrice(address,address[],uint24[])"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseObservationCardinalityNext(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "increaseObservationCardinalityNext(address,address[],uint24[],uint16)"(
      factory: string,
      path: string[],
      fees: BigNumberish[],
      observationCardinalityNext: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
