/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { UniswapV3OracleAdaptorCreator } from "./UniswapV3OracleAdaptorCreator";

export class UniswapV3OracleAdaptorCreatorFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniswapV3OracleAdaptorCreator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as UniswapV3OracleAdaptorCreator;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "adaptor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address[]",
        name: "path",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "uint24[]",
        name: "fees",
        type: "uint24[]",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "shortPeriod",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "longPeriod",
        type: "uint32",
      },
    ],
    name: "NewUniswapV3OracleAdaptor",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "adaptors",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
      {
        internalType: "address[]",
        name: "path",
        type: "address[]",
      },
      {
        internalType: "uint24[]",
        name: "fees",
        type: "uint24[]",
      },
      {
        internalType: "uint32",
        name: "shortPeriod",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "longPeriod",
        type: "uint32",
      },
    ],
    name: "createAdaptor",
    outputs: [
      {
        internalType: "address",
        name: "instance",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address[]",
            name: "path",
            type: "address[]",
          },
          {
            internalType: "uint24[]",
            name: "fees",
            type: "uint24[]",
          },
          {
            internalType: "uint32",
            name: "shortPeriod",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "longPeriod",
            type: "uint32",
          },
        ],
        internalType: "struct UniswapV3OracleAdaptorCreator.AdaptorData",
        name: "adaptorData",
        type: "tuple",
      },
    ],
    name: "getAdaptorDataHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];
